version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: flash-sale-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --requirepass redispass
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "PING"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - redis_data:/data

  mongo:
    image: mongo:7
    container_name: flash-sale-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db

volumes:
  redis_data:
  mongo_data:

