version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: flash-sale-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --requirepass redispass
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "PING"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - redis_data:/data

  mongo:
    image: mongo:7
    container_name: flash-sale-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db

  # --- Backend API ---
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: flash-sale-api
    ports:
      - "4300:4300"
    env_file:
      - .env
    depends_on:
      - mongo
      - redis

  # --- Worker ---
  worker:
    build:
      context: .
      dockerfile: apps/worker/Dockerfile
    container_name: flash-sale-worker
    env_file:
      - .env
    depends_on:
      - mongo
      - redis

  # --- Admin Frontend (Next.js) ---
  admin-web:
    build:
      context: .
      dockerfile: apps/admin-web/Dockerfile
    container_name: flash-sale-admin-web
    ports:
      - "4200:3000"
    env_file:
      - .env
    depends_on:
      - api

  # --- Public Site (Next.js) ---
  site-web:
    build:
      context: .
      dockerfile: apps/site-web/Dockerfile
    container_name: flash-sale-site-web
    ports:
      - "4201:3000"
    env_file:
      - .env
    depends_on:
      - api

volumes:
  redis_data:
  mongo_data:
